### ISSUE TITLE
连续点击两次评论区有概率灰屏

### ISSUE THREAD

**Issue by xumidcm** [orz12/PiliPalaX#129]
### 问题描述
连续点击两次评论区有概率灰屏，在pad端容易触发，因为评论详情在中间展示

### 复现步骤
快速点击两次同一条评论，再关闭

### 预期行为
pad端评论详情移动至右侧，连续点击不会灰屏

### 错误日志

```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: PPR1.180610.011
board: tx20
bootloader: unknown
brand: iFLYTEK
device: IFLYTEKCB
display: iFLY_V1.00.1
fingerprint: SPRD/tx20_c10s/tx20:9/PPR1.180610.011/10141435:user/release-keys
hardware: tx20
host: xxj-ota-b3-2-no
isPhysicalDevice: true
manufacturer: IFLYTEK
model: TX20_C10S
product: AIPad
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 41614
versionPreviewSdk: 0
versionRelease: 9
versionSdk: 28
versionSecurityPatch: 2020-12-05
------- 应用信息 -------
environment: release
version: 1.0.22-beta.3
appName: PiliPalaX
buildNumber: 1653
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
#0      StatefulElement.state (package:flutter/src/widgets/framework.dart:5590)
#1      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:5673)
#2      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2085)
#3      RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#4      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#5      List.forEach (dart:core-patch/growable_array.dart:416)
#6      SliverMultiBoxAdaptorElement.visitChildren (package:flutter/src/widgets/sliver.dart:1057)
#7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#8      RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#10     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#12     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#14     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#16     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#18     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#20     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#22     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#24     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#26     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#28     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#30     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#32     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#34     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#36     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#38     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#39     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#40     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#41     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#42     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#43     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#44     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#45     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#46     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#47     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#48     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#49     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#50     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#51     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#52     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#53     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#54     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#55     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#56     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#57     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#58     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#59     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#60     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#61     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#62     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#63     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#64     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#65     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#66     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#67     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#68     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#69     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#70     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#71     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#72     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#73     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#74     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#75     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#76     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#77     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#78     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#79     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#80     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#81     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#82     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#83     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#84     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#85     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#86     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#87     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#88     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#89     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#90     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#91     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#92     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#93     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#94     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#95     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#96     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#97     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#98     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#99     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#100    _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#101    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#102    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#103    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#104    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#105    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#106    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#107    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#108    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#109    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#110    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#111    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2087)
#112    _InactiveElements.add (package:flutter/src/widgets/framework.dart:2099)
#113    Element.deactivateChild (package:flutter/src/widgets/framework.dart:4368)
#114    Element.updateChildren (package:flutter/src/widgets/framework.dart:4059)
#115    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#119    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#122    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#124    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#127    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#129    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#133    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#136    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#138    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#140    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#144    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#146    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#149    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#151    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#154    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#155    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#156    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#160    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#164    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#168    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#171    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#172    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#173    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#174    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#176    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#177    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#180    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#182    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895)
#183    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984)
#184    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#185    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#186    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#187    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#188    _invoke (dart:ui/hooks.dart:312)
#189    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#190    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------
```

### 相关信息

https://github.com/user-attachments/assets/80a90335-58e4-4c19-a8c7-dd8e24d4ca54

**Comment by VillagerTom** [comment]
最新版已无此bug.

**Comment by VillagerTom** [comment]
另，

> ### 预期行为
> pad端评论详情移动至右侧，

与#305 重复。
