### ISSUE TITLE
BUG: 消息列表底部的灰色区域

### ISSUE THREAD

**Issue by lingbopro** [orz12/PiliPalaX#130]
### 问题描述
消息列表底部有一片灰色区域

### 复现步骤
点击首页右上角的消息图标，进入消息列表

### 预期行为
不应有灰色区域

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: HUAWEIEVR-AL00
board: EVR
bootloader: unknown
brand: HUAWEI
device: HWEVR
display: EVR-AL00 10.1.0.163(C00E160R2P8)
fingerprint: HUAWEI/EVR-AL00/HWEVR:10/HUAWEIEVR-AL00/10.1.0.163C00:user/release-keys
hardware: kirin980
host: cn-central-1b-564e7048f1595385991956-1606187626-f78qj
isPhysicalDevice: true
manufacturer: HUAWEI
model: EVR-AL00
product: EVR-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 10.1.0.163C00
versionPreviewSdk: 0
versionRelease: 10
versionSdk: 29
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.0.22-beta.3
appName: PiliPalaX
buildNumber: 1653
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
NoSuchMethodError: The getter 'face' was called on null.
Receiver: null
Tried calling: face
------- 错误堆栈 -------
#0      _WhisperPageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:PiliPalaX/pages/whisper/view.dart:204)
#1      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1422)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490)
#3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:829)
#4      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:843)
#5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835)
#6      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:835)
#7      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349)
#8      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657)
#9      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071)
#10     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657)
#11     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338)
#12     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:486)
#13     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239)
#14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:281)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601)
#20     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1925)
#21     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1876)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#23     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#26     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#29     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#41     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#46     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#49     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
#50     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808)
#51     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#54     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:494)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#56     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#59     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#62     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#65     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#68     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#71     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#74     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#77     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#79     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#81     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#82     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
#83     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:581)
#84     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:608)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#86     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#87     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173)
#88     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062)
#89     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237)
#90     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403)
#91     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385)
#92     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025)
#93     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038)
#94     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591)
#95     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986)
#96     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#97     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#98     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#99     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#100    _invoke (dart:ui/hooks.dart:312)
#101    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#102    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------
```

APP版本: `1.0.22-beta3+165`  
系统: `HarmonyOS 3 (Android 10)`  
设备: `HUAWEI Mate 20 Pro`

### 相关信息
![Screenshot_20240714_145754_com.orz12.PiliPalaX.jpg](https://github.com/user-attachments/assets/ceea76ea-93c0-43f5-835d-0b3f7fcc768d)

**Comment by orz12** [comment]
已尝试修复

**Comment by lingbopro** [comment]
![Screenshot_20240723_074649_com.orz12.PiliPalaX.jpg](https://github.com/user-attachments/assets/2cff43b2-81c9-4f78-ac47-553a6b6eb9f3)

现在没问题了
