### ISSUE TITLE
退出视频后蓝牙耳机仍可控制播放

### ISSUE THREAD

**Issue by cheeserick** [orz12/PiliPalaX#14]
### 问题描述
见复现步骤

### 复现步骤
1.连接具有播放/暂停控制功能的蓝牙耳机
2.播放视频
3.暂停视频（蓝牙耳机控制或屏幕控制均可）
4.退出视频
5.按下蓝牙耳机的播放/暂停键，视频声音会继续在后台播放，此时无法用耳机控制暂停，通知栏无媒体控制选项
6.播放其他视频或划掉app卡片，声音停止

### 预期行为
修复上述问题。

### 错误日志
```
PiliPalaX错误日志 
 ********************
------- 设备信息 -------
id: 58.2.A.10.126
board: kona
bootloader: xboot
brand: Sony
device: XQ-AS72
display: 58.2.A.10.126
fingerprint: Sony/XQ-AS72/XQ-AS72:12/58.2.A.10.126/058002A010012603718185433:user/release-keys
hardware: qcom
host: BuildHost
isPhysicalDevice: true
manufacturer: Sony
model: XQ-AS72
product: XQ-AS72
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 058002A010012603718185433
versionPreviewSdk: 0
versionRelease: 12
versionSdk: 31
versionSecurityPatch: 2022-10-01
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPalaX
buildNumber: 1253
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:56)
<asynchronous suspension>
------- CUSTOM INFO -------
```

### 相关信息
录屏见[网盘链接](https://drive.google.com/file/d/1kkIkZnCfWxcy5snYd9kmwUuE8neUhUcq)（压缩了一下，有点音画不同步，不影响理解）

**Comment by orz12** [comment]
这可能是音频焦点产生的故障。原版是否有此问题？

**Comment by cheeserick** [comment]
> 这可能是音频焦点产生的故障。原版是否有此问题？

原版也有一模一样的问题

**Comment by cheeserick** [comment]
> 这块我的了解有限 建议你跟原作者也沟通一下看看 他有没有什么想法

原版那边有人也提到了[类似的bug](https://github.com/guozhigq/pilipala/issues/440)，复现过程不太一样，明天我再去提一下

**Comment by orz12** [comment]
这个bug我修过了 但我发现 修好以后的代价是 蓝牙耳机在后台可以暂停 但不能在后台恢复播放 跟你的症状有一点不一样

**Comment by VillagerTom** [comment]
最新版还有此问题吗？

**Comment by VillagerTom** [comment]
v1.1.0测试此bug已修复。
