### ISSUE TITLE
弹幕屏蔽词没有自动加载

### ISSUE THREAD

**Issue by shibuyameltdown** [orz12/PiliPalaX#148]
### 问题描述
如题
### 复现步骤
点进任意视频能看到未经屏蔽的弹幕，需要手动点进屏蔽词管理，跳出已同步屏蔽词弹窗后返回播放界面，才能显示被屏蔽后弹幕
### 预期行为
屏蔽词被正确加载，显示屏蔽后弹幕

PiliPalaX错误日志
********************
------- 设备信息 -------
id: UP1A.231005.007
board: tb8796p1_64_sp
bootloader: unknown
brand: vivo
device: DPD2329
display: UP1A.231005.007 release-keys
fingerprint: vivo/DPD2329/DPD2329:14/UP1A.231005.007/compiler07121857:user/release-keys
hardware: mt8796
host: comdg01146224
isPhysicalDevice: true
manufacturer: vivo
model: PA2473
product: DPD2329
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: compiler07121857
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-06-01
------- 应用信息 -------
environment: release
version: 1.0.22-beta.2
appName: PiliPalaX
buildNumber: 1643
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Bad state: No element
------- 错误堆栈 -------
#0      List.single (dart:core-patch/growable_array.dart:353)
#1      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:159)
#2      ScrollController.offset (package:flutter/src/widgets/scroll_controller.dart:165)
#3      DynamicsTabController.animateToTop (package:PiliPalaX/pages/dynamics/tab/controller.dart:68)
#4      _DynamicsPageState.build.<anonymous closure> (package:PiliPalaX/pages/dynamics/view.dart:151)
#5      _TabBarState._handleTap (package:flutter/src/material/tabs.dart:1475)
#6      _TabBarState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:1631)
#7      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439)
#21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#25     _invoke1 (dart:ui/hooks.dart:328)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
------- CUSTOM INFO -------

**Comment by CICILC** [comment]
+1
