### ISSUE TITLE
[Bug] 推荐页面（首页）为空白

### ISSUE THREAD

**Issue by imzoet** [orz12/PiliPalaX#158]
### 问题描述
登录后推荐页面空白

### 复现步骤
登录后首页空白

### 预期行为
正确显示推荐视频

### 错误日志
`PiliPalaX错误日志
********************
------- 设备信息 -------
id: UKQ1.230804.001
board: houji
bootloader: unknown
brand: Xiaomi
device: houji
display: UKQ1.230804.001 release-keys
fingerprint: Xiaomi/houji/houji:14/UKQ1.230804.001/V816.0.42.0.UNCCNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-295147-mn7q0-gphts-97084
isPhysicalDevice: true
manufacturer: Xiaomi
model: 23127PN0CC
product: houji
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V816.0.42.0.UNCCNXM
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-06-01
------- 应用信息 -------
environment: release
version: 1.0.22-beta.5
appName: PiliPalaX
buildNumber: 1673
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
RangeError (length): Invalid value: Valid value range is empty: 0
------- 错误堆栈 -------
#0      HomeController.animateToTop (package:PiliPalaX/pages/home/controller.dart)
#1      _MainAppState.setIndex (package:PiliPalaX/pages/main/view.dart:56)
#2      _MainAppState.build.<anonymous closure>.<anonymous closure> (package:PiliPalaX/pages/main/view.dart:228)
#3      NavigationBar._handleTap.<anonymous closure> (package:flutter/src/material/navigation_bar.dart:211)
#4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#17     _invoke1 (dart:ui/hooks.dart:328)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
------- CUSTOM INFO -------`

### 相关信息

![c154b3517a0410d28939176371e914a](https://github.com/user-attachments/assets/d8773739-ffdc-4cc6-a680-e08825b61ed0)
![be198c42f222738737027be861a276b](https://github.com/user-attachments/assets/2de57b4c-1a97-49bd-9542-fbeeb6fd0a91)
![8376202d8455d713ed072ce3eb9d3ec](https://github.com/user-attachments/assets/29e4a9c3-b028-4080-a741-b0734353694f)

**Comment by imzoet** [comment]
非bug，本人设置有误
