### ISSUE TITLE
[Bug] 查看自己的动态后并返回后灰屏

### ISSUE THREAD

**Issue by lingbopro** [orz12/PiliPalaX#170]
### 问题描述
如题

### 复现步骤
在动态中打开自己的一个动态并返回会导致灰屏

### 预期行为
不应灰屏

### 错误日志

APP: `1.0.22-beta.7+169`

<details>
<summary>错误日志</summary>

```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: HUAWEIEVR-AL00
board: EVR
bootloader: unknown
brand: HUAWEI
device: HWEVR
display: EVR-AL00 10.1.0.163(C00E160R2P8)
fingerprint: HUAWEI/EVR-AL00/HWEVR:10/HUAWEIEVR-AL00/10.1.0.163C00:user/release-keys
hardware: kirin980
host: cn-central-1b-564e7048f1595385991956-1606187626-f78qj
isPhysicalDevice: true
manufacturer: HUAWEI
model: EVR-AL00
product: EVR-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 10.1.0.163C00
versionPreviewSdk: 0
versionRelease: 10
versionSdk: 29
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.0.22-beta.7
appName: PiliPalaX
buildNumber: 1693
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
#0      Element.widget (package:flutter/src/widgets/framework.dart:3474)
#1      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:301)
#2      RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#3      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#4      _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#5      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#6      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#7      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#8      _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#9      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#10     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#11     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#12     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#13     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#14     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#15     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#16     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#17     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#18     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#19     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#20     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#21     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#22     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#23     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#24     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#25     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#26     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#27     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#28     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#29     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#30     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#31     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#32     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#33     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#34     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#35     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#36     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#37     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#38     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#39     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#40     _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:338)
#41     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#42     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#43     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#44     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#45     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#46     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#47     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#48     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#49     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#50     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#51     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#52     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#53     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#54     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#55     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#56     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#57     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#58     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#59     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#60     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#61     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#62     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#63     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#64     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#65     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#66     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#67     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#68     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#69     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#70     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#71     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#72     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#73     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#74     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#75     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#76     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#77     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#78     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#79     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#80     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#81     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#82     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#83     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#84     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#85     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#86     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#87     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#88     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#89     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#90     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#91     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#92     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#93     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#94     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#95     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#96     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#97     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#98     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#99     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#100    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#101    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#102    _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#103    Element.visitChildElements (package:flutter/src/widgets/framework.dart:3711)
#104    Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:324)
#105    HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:945)
#106    HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:904)
#107    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#108    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264)
#109    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#110    _invoke (dart:ui/hooks.dart:312)
#111    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#112    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------
```

</details>

错误日志如上，还有一个不知何意的名称为`null`的日志：
![Screenshot_20240813_173021_com.orz12.PiliPalaX.jpg](https://github.com/user-attachments/assets/45260718-20cd-489e-89a1-a47342e200aa)

### 相关信息
录屏如下：

https://github.com/user-attachments/assets/c2f8ac8a-ad48-401c-9c6c-f5869fd1142f

**Comment by lingbopro** [comment]
另外我发现其他UP主的动态也有可能触发，但是我只偶尔复现了几次，都没录

**Comment by orz12** [comment]
更新了，评论区的问题

**Comment by VillagerTom** [comment]
新版是否还有问题？

**Comment by lingbopro** [comment]
现在不会白屏了，不过我在#138 中说的问题（横屏模式下切换合集分集顶部标题不会改变）还能复现
