### ISSUE TITLE
[Bug] 平板横屏下直播间返回动态界面会变回竖屏再快速变为横屏

### ISSUE THREAD

**Issue by yizhimengxin2233** [orz12/PiliPalaX#171]
### 问题描述
如题，当开启平板横屏模式下从直播间界面返回动态界面下会先变回竖屏再快速变为横屏

### 复现步骤
1.开启横屏模式
2.切换至动态界面
3.从动态打开某一直播间
4.使用返回手势推出
5.复现

### 预期行为
保持横屏

### 错误日志
（可能与该bug无关）
~~~
PiliPalaX错误日志
********************
------- 设备信息 -------
id: UP1A.231005.007
board: taro
bootloader: X800ZCS8CXG5
brand: samsung
device: gts8pwifi
display: UP1A.231005.007.X800ZCS8CXG5
fingerprint: samsung/gts8pwifizc/gts8pwifi:14/UP1A.231005.007/X800ZCS8CXG5:user/release-keys
hardware: qcom
host: 21DKG907
isPhysicalDevice: true
manufacturer: samsung
model: SM-X800
product: gts8pwifizc
tags: release-keys
type: user
versionBaseOs: samsung/gts8pwifizc/gts8pwifi:14/UP1A.231005.007/X800ZCU6CXE4:user/release-keys
versionCodename: REL
versionIncremental: X800ZCS8CXG5
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-05-01
------- 应用信息 -------
environment: release
version: 1.0.22-beta.7
appName: PiliPalaX
buildNumber: 1693
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
#0      Element.widget (package:flutter/src/widgets/framework.dart:3474)
#1      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:301)
#2      RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#3      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#4      _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#5      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#6      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#7      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#8      _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#9      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#10     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#11     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#12     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#13     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#14     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#15     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#16     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#17     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#18     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#19     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#20     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#21     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#22     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#23     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#24     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#25     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#26     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#27     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#28     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#29     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#30     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#31     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#32     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#33     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#34     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#35     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#36     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#37     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#38     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#39     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#40     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#41     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#42     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#43     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#44     _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:338)
#45     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#46     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#47     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#48     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#49     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#50     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#51     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#52     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#53     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#54     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#55     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#56     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#57     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#58     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#59     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#60     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#61     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#62     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#63     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#64     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#65     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#66     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6834)
#67     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#68     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#69     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#70     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#71     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#72     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#73     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#74     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#75     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#76     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#77     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#78     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#79     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#80     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#81     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#82     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#83     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#84     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#85     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#86     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#87     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#88     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#89     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#90     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#91     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#92     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#93     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#94     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#95     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#96     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#97     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#98     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#99     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#100    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#101    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#102    _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#103    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#104    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#105    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321)
#106    _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#107    Element.visitChildElements (package:flutter/src/widgets/framework.dart:3711)
#108    Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:324)
#109    HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:945)
#110    HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:904)
#111    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#112    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264)
#113    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#114    _invoke (dart:ui/hooks.dart:312)
#115    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#116    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------
~~~

### 相关信息

https://github.com/user-attachments/assets/cc391113-f05e-4a7b-a8ff-be7a6eb37fac

**Comment by orz12** [comment]
直播间暂时没有精力维护
