### ISSUE TITLE
[Bug] 专栏内容无法显示

### ISSUE THREAD

**Issue by lingbopro** [orz12/PiliPalaX#250]
### 问题描述

如题

直接从评论区链接打开会页面空白，从观看历史进入会没有正文

### 复现步骤

打开一个专栏（不确定是否具有普遍性，可用[cv34082421](https://www.bilibili.com/read/cv34082421)测试）

### 预期行为

应正常打开并显示内容

### 错误日志

```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: HUAWEIEVR-AL00
board: EVR
bootloader: unknown
brand: HUAWEI
device: HWEVR
display: EVR-AL00 10.1.0.163(C00E160R2P8)
fingerprint: HUAWEI/EVR-AL00/HWEVR:10/HUAWEIEVR-AL00/10.1.0.163C00:user/release-keys
hardware: kirin980
host: cn-central-1b-564e7048f1595385991956-1606187626-f78qj
isPhysicalDevice: true
manufacturer: HUAWEI
model: EVR-AL00
product: EVR-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 10.1.0.163C00
versionPreviewSdk: 0
versionRelease: 10
versionSdk: 29
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.0.22-beta.12
appName: PiliPalaX
buildNumber: 1743
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
#0      HtmlHttp.reqReadHtml (package:PiliPalaX/http/html.dart:76)
<asynchronous suspension>
#1      HtmlRenderController.reqHtml (package:PiliPalaX/pages/html/controller.dart:54)
<asynchronous suspension>
------- CUSTOM INFO -------
```

### 相关信息

录屏（从评论区链接进入）：

https://github.com/user-attachments/assets/0f3805fc-381c-49de-a0c8-80acde7b1134

截图（观看历史进入）：

![观看历史进入时的图片，没有正文内容](https://github.com/user-attachments/assets/b9f9a888-312c-4570-ba7a-19a3d9627367)

**Comment by orz12** [comment]
已修复
