### ISSUE TITLE
[Bug] 瀑布流滑动卡顿严重

### ISSUE THREAD

**Issue by 00susu00** [orz12/PiliPalaX#251]
### 问题描述
设备小新pad pro12.7骁龙870 120hz高刷 瀑布流滑动卡顿严重
请提供一个清晰而简明的问题描述。

### 复现步骤
稳定复现
请提供复现该问题所需的具体步骤。

### 预期行为
尝试了网页端一切正常 b站hd客户端一切正常
请描述你期望的正确行为或结果。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: UKQ1.231222.001
board: spinel
bootloader: unknown
brand: Lenovo
device: TB371FC
display: TB371FC_CN_OPEN_USER_Q00028.1_U_ZUI_16.0.430_ST_240819
fingerprint: Lenovo/TB371FC_PRC/TB371FC:14/UKQ1.231222.001/ZUI_16.0.430_240819_PRC:user/release-keys
hardware: qcom
host: hqsl009
isPhysicalDevice: true
manufacturer: LENOVO
model: TB371FC
product: TB371FC_PRC
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: TB371FC_CN_OPEN_USER_Q00028.1_U_ZUI_16.0.430_ST_240819
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-06-05
------- 应用信息 -------
environment: release
version: 1.0.22-beta.12
appName: PiliPalaX
buildNumber: 1743
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
FormatException: Unexpected character (at character 1)
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
^
------- 错误堆栈 -------
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SearchHttp.searchSuggest (package:PiliPalaX/http/search.dart:43)
<asynchronous suspension>
#7      SSearchController.querySearchSuggest (package:PiliPalaX/pages/search/controller.dart:105)
<asynchronous suspension>
------- CUSTOM INFO -------
```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by orz12** [comment]
请尝试关闭自动收起顶栏/底栏 但本身列表滑动的优化就很复杂 不是专业的 只能做到这样了（
