### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by cgykcftyi** [orz12/PiliPalaX#261]
### 问题描述
在首页推荐流点击充电视频直接白屏

### 复现步骤
1.在首页找到充电视频；2.直接点击此视频

### 预期行为
在首页推荐流点击的充电视频正常进入

### 错误日志

```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: HUAWEIDUK-AL20
board: DUK
bootloader: unknown
brand: HONOR
device: HWDUK
display: DUK-AL20 9.1.0.225(C00E125R1P9)
fingerprint: HONOR/DUK-AL20/HWDUK:9/HUAWEIDUK-AL20/9.1.0.225C00:user/release-keys
hardware: hi3660
host: 秘密
isPhysicalDevice: true
manufacturer: HUAWEI
model: DUK-AL20
product: DUK-AL20
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 9.1.0.225C00
versionPreviewSdk: 0
versionRelease: 9
versionSdk: 28
versionSecurityPatch: 2020-05-01
------- 应用信息 -------
environment: release
version: 1.0.22-beta.12
appName: PiliPalaX
buildNumber: 1743
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
RangeError (length): Invalid value: Valid value range is empty: 3
------- 错误堆栈 -------
#0      IdUtils.bv2av (package:PiliPalaX/utils/id_utils.dart)
#1      VideoDetailController.onInit (package:PiliPalaX/pages/video/detail/controller.dart:153)
#2      GetLifeCycleBase._onStart (package:get/get_instance/src/lifecycle.dart:66)
#3      InternalFinalCallback.call (package:get/get_instance/src/lifecycle.dart:12)
#4      GetInstance._startController (package:get/get_instance/src/get_instance.dart:254)
#5      GetInstance._initDependencies (package:get/get_instance/src/get_instance.dart:205)
#6      GetInstance.find (package:get/get_instance/src/get_instance.dart:302)
#7      GetInstance.put (package:get/get_instance/src/get_instance.dart:87)
#8      Inst.put (package:get/get_instance/src/extension_instance.dart:89)
#9      _VideoDetailPageState.initState (package:PiliPalaX/pages/video/detail/view.dart:79)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5748)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#48     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#74     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#90     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#93     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#104    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#112    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#115    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#124    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#125    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#128    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#132    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#133    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#134    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#135    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#136    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#140    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#141    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#152    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#155    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#156    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#157    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#158    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#160    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#161    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#162    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#171    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#175    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#176    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#177    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#182    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#183    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#184    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#185    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#187    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#188    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#189    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#190    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#191    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#192    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#193    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#194    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#195    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#196    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#197    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#198    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#201    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#203    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#204    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#205    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#206    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#207    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#209    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#210    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#212    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#214    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#215    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#216    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#220    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#221    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#226    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#227    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#228    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#229    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#230    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#231    Eleme.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#232    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#233    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#234    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#235    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#236    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#237    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#238    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#239    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#240    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035)
#241    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#242    Element.updateChildren (package:flutter/src/widgets/framework.dart:4150)
#243    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7060)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#245    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#246    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#247    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#248    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803)
#249    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#251    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#252    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946)
#253    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#254    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#255    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#256    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946)
#257    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#258    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#259    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#260    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#261    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#262    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803)
#263    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#264    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#265    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#266    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946)
#267    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#268    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#269    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#270    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#271    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#272    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803)
#273    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#274    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#275    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#276    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#277    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803)
#278    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#279    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907)
#280    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#281    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907)
#282    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#283    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#284    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#285    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946)
#286    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#287    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#288    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#289    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946)
#290    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#291    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#292    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#293    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#294    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693)
#295    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752)
#296    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048)
#297    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162)
#298    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468)
#299    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#300    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318)
#301    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
#302    _invoke (dart:ui/hooks.dart:312)
#303    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#304    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------
```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by bggRGjQaUbCoE** [comment]
`bvid = json['player_args'] != null
        ? IdUtils.av2bv(json['player_args']['aid'])
        : '';`
这里的问题
