### ISSUE TITLE
[Bug] 接口更新导致无法搜索观看记录

### ISSUE THREAD

**Issue by VillagerTom** [orz12/PiliPalaX#284]
### 问题描述
观看记录页搜索功能失效。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: N2G47H
board: msm8952
bootloader: unknown
brand: vivo
device: PD1619
display: N2G47H release-keys
fingerprint: vivo/PD1619/PD1619:7.1.2/N2G47H/compil09211709:user/release-keys
hardware: qcom
host: compiler030
isPhysicalDevice: true
manufacturer: vivo
model: vivo X9Plus
product: PD1619
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: eng.compil.20220921.170934
versionPreviewSdk: 0
versionRelease: 7.1.2
versionSdk: 25
versionSecurityPatch: 2019-10-01
------- 应用信息 -------
environment: release
version: 1.0.22-beta.12
appName: PiliPalaX
buildNumber: 1743
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
type 'String' is not a subtype of type 'int' of 'index'
------- 错误堆栈 -------
#0      UserHttp.searchHistory (package:PiliPalaX/http/user.dart:308)
<asynchronous suspension>
#1      HistorySearchController.searchHistories (package:PiliPalaX/pages/history_search/controller.dart:48)
<asynchronous suspension>
------- CUSTOM INFO -------
```

**Comment by VillagerTom** [comment]
35b502ff740d72971d88537b6146caed92b7a449
