### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zbc258** [orz12/PiliPalaX#290]
### 问题描述
当从首页进入视频时，有概率无法播放，必须切换一次播放清晰度才能正常播放。若当前默认播放清晰度高于该视频支持的清晰度，则必定无法播放，必须手动更改默认清晰度才能播放。如果从视频下方推荐进入其他视频，则该问题必定触发。

### 复现步骤
1.在设置中将默认清晰度调高，比如调成“8K超高清”，从首页直接打开一个视频，有一定概率会一直卡在缓冲，无法播放，并提示视频打开失败；
2.在视频中切换默认清晰度，如从8K超高清切换到720p，视频开始正常播放；
3.将清晰度切换回8K超高清（如果有），视频仍能正常播放并完成清晰度切换。
4.从该视频下方的推荐打开一个视频，必定触发1，如果按2、3操作，又可正常播放。
### 预期行为
若设置的默认清晰度高于该视频可用的清晰度，应该按顺序选择该视频可用的第一个清晰度，比如设置8K超高清，但可用清晰度最高只有1080p，应自动选择1080p进行播放。
### 错误日志
PiliPalaX错误日志
********************
------- 设备信息 -------
id: HUAWEILIO-AN00
board: LIO
bootloader: unknown
brand: HUAWEI
device: HWLIO
display: LIO-AN00 4.2.0.120(SP1C00E100R6P4)
fingerprint: HUAWEI/LIO-AN00/HWLIO:12/HUAWEILIO-AN00/104.2.0.120SP1C00:user/release-keys
hardware: kirin990
host: cn-west-hcd-5a-4ab28ff6b1716342148897-9855cbb48-r824r
isPhysicalDevice: true
manufacturer: HUAWEI
model: LIO-AN00
product: LIO-AN00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 104.2.0.120SP1C00
versionPreviewSdk: 0
versionRelease: 12
versionSdk: 31
versionSecurityPatch: 2021-10-05
------- 应用信息 -------
environment: release
version: 1.0.22-beta.12
appName: PiliPalaX
buildNumber: 1743
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Bad state: No element
------- 错误堆栈 -------
#0      Stream.first.<anonymous closure> (dart:async/stream.dart:1583)
#1      _RootZone.runGuarded (dart:async/zone.dart:1582)
#2      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418)
#3      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428)
#4      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317)
#5      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99)
#6      _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161)
#7      _RootZone.runGuarded (dart:async/zone.dart:1582)
#8      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418)
#9      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428)
#10     _DelayedDone.perform (dart:async/stream_impl.dart:560)
#11     _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
------- CUSTOM INFO -------
### 相关信息
设备型号：华为mate30pro、华为matepad pro2024，系统版本均为鸿蒙4.2，PiliPalaX版本均为1.022-beta.12+174

**Comment by VillagerTom** [comment]
有大会员吗？

**Comment by VillagerTom** [comment]
描述前后矛盾。上面说实验视频“切换回8K能正常播放”，下面又说没有更高清晰度时才会出现bug。

请使用控制变量法重新测试后，仔细报告实际情况。

**Comment by zbc258** [comment]
> 描述前后矛盾。上面说实验视频“切换回8K能正常播放”，下面又说没有更高清晰度时才会出现bug。
> 
> 请使用控制变量法重新测试后，仔细报告实际情况。

没有矛盾，因为本app里无论是在视频播放界面，还是在设置界面里进行设置，提示设置的都是“默认清晰度”，而不是播放本视频的清晰度，所以在3中标注了“如果有”。即使该视频没有8K清晰度，只要进行一次默认清晰度的更改，比如从720p改成1080p，或者1080p改成720p，就能正常播放，不管是比之前的高还是低。
而之所以这样描述，是因为这个问题并不固定在某个视频下发生，如果更改一次后可以正常播放，再次播放就不会触发。而在视频下方的推荐中点入其他视频，该问题触发的尤其频繁。
同时我又仔细的测试了一番，发现不仅在默认清晰度设置过高时会出现此问题，过低（如360P）时一样有可能发生，同样，在播放界面选择默认画质里更改一次默认画质就能正常播放，报错信息与上面相同。

**Comment by VillagerTom** [comment]
默认画质分别为1080p+及以上时，是否有相同情况？

**Comment by zbc258** [comment]
> 默认画质分别为1080p+及以上时，是否有相同情况？

有，我这两天一直在反复测试，默认画质直接设1080p或者720p会减少这个问题的触发（但不是没有）；
首选解码格式如果设成HEVC会大大增加该问题触发概率；
默认音质设太高或者太低也有几率卡加载或者无声。
此外，在上游版本https://github.com/guozhigq/pilipala进行同样的设置时未出现此问题。

**Comment by orz12** [comment]
这个目前版本做了一定程度的修复 可以观察一下是否有效果
