### ISSUE TITLE
[Bug] 用戶詳情頁頭像暱稱消失

### ISSUE THREAD

**Issue by onichan0923** [orz12/PiliPalaX#324]
### 问题描述
用戶詳情頁頭像於暱稱出現一下後馬上消失，下方組件隨之上移

### 复现步骤
點擊任意用戶頭像進入詳情頁，共兩台設備在1.0.22-beta.12+174均成功復現

### 预期行为
頭像與暱稱組件常駐顯示

### 错误日志
```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: U1TRS34.8-30-18-4
board: rtwo
bootloader: MBM-3.0-rtwo-b08290d629f-240902-U1TRS34.8-30-18-4-f6c089
brand: motorola
device: rtwo
display: U1TRS34.8-30-18-4
fingerprint: motorola/rtwo_g/rtwo:14/U1TRS34.8-30-18-4/f6c089-eda59a:user/release-keys
hardware: qcom
host: ilclbld178
isPhysicalDevice: true
manufacturer: motorola
model: motorola edge 40 pro
product: rtwo_g
tags: release-keys
type: user
versionBaseOs: motorola/rtwo_g/rtwo:14/U1TR34.8-30-18/8b7b26-b62c4:user/release-keys
versionCodename: REL
versionIncremental: f6c089-eda59a
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-09-01
------- 应用信息 -------
environment: release
version: 1.0.22-beta.12
appName: PiliPalaX
buildNumber: 1743
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
#0      NetworkImgLayer.build (package:PiliPalaX/common/widgets/network_img_layer.dart:43)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:5687)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#50     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#53     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035)
#54     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047)
#55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#58     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#65     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#78     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#81     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035)
#82     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047)
#83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#86     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#106    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#108    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035)
#109    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047)
#110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#119    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#121    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#122    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#123    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#127    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#129    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#130    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#131    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#132    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#136    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#137    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#141    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#142    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#144    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#145    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#148    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#152    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#157    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#158    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#161    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#162    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#164    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#165    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#169    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#170    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#171    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#172    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#173    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#177    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#178    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#179    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#180    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#183    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#184    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#185    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#186    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#187    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#189    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#190    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#191    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#192    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#193    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#194    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#195    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#196    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#197    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#198    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#201    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#203    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#204    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#205    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#206    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#207    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#209    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#210    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#211    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#212    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#213    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#214    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#215    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035)
#216    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047)
#217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#220    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#221    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#225    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#226    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#227    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#229    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
```

### 相关信息
https://github.com/user-attachments/assets/1f18047f-118a-48dc-9365-12ea1d5cff47
https://github.com/user-attachments/assets/d82b6857-7fe0-4fa0-8567-c3b82bb4f2b8

**Comment by VillagerTom** [comment]
与#274 重复。

**Comment by orz12** [comment]
新版已解决 请更新
