### ISSUE TITLE
[Bug]  音频丢失？退出视频重新打开可以概率解决

### ISSUE THREAD

**Issue by NeoSnape** [orz12/PiliPalaX#326]
### 问题描述
首页打开视频有概率没声音

### 复现步骤
首页打开视频

### 预期行为
正常播放有声音

### 错误日志

丢失声音的时候并没有产生错误日志 安卓15  Color OS 15 
```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: AP3A.240617.008
board: sun
bootloader: unknown
brand: OnePlus
device: OP5D0DL1
display: PJZ110_15.0.0.301(CN01)
fingerprint: OnePlus/PJZ110/OP5D0DL1:15/AP3A.240617.008/V.1b232c4-1_1:user/release-keys
hardware: qcom
host: dg02-pool07-kvm28
isPhysicalDevice: true
manufacturer: OnePlus
model: PJZ110
product: PJZ110
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V.1b232c4-1_1
versionPreviewSdk: 0
versionRelease: 15
versionSdk: 35
versionSecurityPatch: 2024-11-05
------- 应用信息 -------
environment: release
version: 1.0.22
appName: PiliPalaX
buildNumber: 1623
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
LateInitializationError: Field 'videoUrl' has not been initialized.
------- 错误堆栈 -------
#0      VideoDetailController.playerInit (package:PiliPalaX/pages/video/detail/controller.dart)
#1      _VideoDetailPageState.didPopNext (package:PiliPalaX/pages/video/detail/view.dart:317)
#2      RouteObserver.didPop (package:flutter/src/widgets/routes.dart:2000)
#3      _NavigatorPopObservation.notify (package:flutter/src/widgets/navigator.dart:3350)
#4      List.forEach (dart:core-patch/growable_array.dart:416)
#5      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:4338)
#6      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4295)
#7      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5255)
#8      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5204)
<asynchronous suspension>
#9      WidgetsBinding.handlePopRoute (package:flutter/src/widgets/binding.dart:737)
<asynchronous suspension>
#10     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:559)
<asynchronous suspension>
#11     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567)
<asynchronous suspension>
------- CUSTOM INFO -------
```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by lingbopro** [comment]
我也遇到过，应该是取流失败，重载一下视频就行

**Comment by orz12** [comment]
你甚至没有升到新版本就来提问

**Comment by NeoSnape** [comment]
> 你甚至没有升到新版本就来提问

来升级顺便提问下的捏，新版很少出现

**Comment by orz12** [comment]
> 来升级顺便提问下的捏，新版很少出现
之后得研究下怎么触发音频的重试机制 我估计不好做
