### ISSUE TITLE
[Bug] 动态页面无法切换UP

### ISSUE THREAD

**Issue by lingbopro** [orz12/PiliPalaX#333]
### 问题描述
如题，切换侧边栏的up后右侧未切换到对应up

### 复现步骤
见视频

### 预期行为
应切换到选择的up

### 错误日志

```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: HUAWEIEVR-AL00
board: EVR
bootloader: unknown
brand: HUAWEI
device: HWEVR
display: EVR-AL00 10.1.0.163(C00E160R2P8)
fingerprint: HUAWEI/EVR-AL00/HWEVR:10/HUAWEIEVR-AL00/10.1.0.163C00:user/release-keys
hardware: kirin980
host: cn-central-1b-564e7048f1595385991956-1606187626-f78qj
isPhysicalDevice: true
manufacturer: HUAWEI
model: EVR-AL00
product: EVR-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 10.1.0.163C00
versionPreviewSdk: 0
versionRelease: 10
versionSdk: 29
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.1.0
appName: PiliPalaX
buildNumber: 1753
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
#0      Directionality.of (package:flutter/src/widgets/basic.dart:178)
#1      _TabBarState._tabScrollOffset (package:flutter/src/material/tabs.dart:1523)
#2      _TabBarState._tabCenteredScrollOffset (package:flutter/src/material/tabs.dart:1536)
#3      _TabBarState._scrollToCurrentIndex (package:flutter/src/material/tabs.dart:1544)
#4      _TabBarState._handleTabControllerTick (package:flutter/src/material/tabs.dart:1579)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:437)
#6      TabController._changeIndex (package:flutter/src/material/tab_controller.dart:221)
#7      TabController.index= (package:flutter/src/material/tab_controller.dart:237)
#8      DynamicsController.onSelectUp (package:PiliPalaX/pages/dynamics/controller.dart:303)
#9      _UpPanelState.upItemBuild.<anonymous closure> (package:PiliPalaX/pages/dynamics/widgets/up_panel.dart:127)
#10     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170)
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351)
#12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656)
#13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313)
#14     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:283)
#15     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:169)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:505)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305)
#23     _invoke1 (dart:ui/hooks.dart:328)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
------- CUSTOM INFO -------
```

### 相关信息

https://github.com/user-attachments/assets/582e903a-8e6a-4a2e-879d-a4d6c8fbbc1c

**Comment by orz12** [comment]
没有前置步骤 无法复现
不过这次修了一些别的动态bug 可以尝试一下是否有顺带修复

**Comment by lingbopro** [comment]
> 没有前置步骤 无法复现

是这样的，只能偶然复现

（不过从动态打开视频再回来或者息屏/切后台有时候能复现

**Comment by orz12** [comment]
那我估计应该是修了 你下载pre-release里面的beta版试下

**Comment by lingbopro** [comment]
后来我确实没遇到了
