### ISSUE TITLE
横屏模式下分集切换异常

### ISSUE THREAD

**Issue by BakaJzon** [orz12/PiliPalaX#67]
### 问题描述
在平板横屏模式下，点击分集切换无效，同时点击 `分集列表-任意分集` 有提示但是视频照常播放。
前置条件：推荐视频未加载

### 复现步骤
1. 切换横屏模式（因为竖屏推荐与分集在同一页）
2. 外观设置-默认展示评论区 On
3. 随意有分集的视频，切换无效
4. **临时解决**：左划加载推荐视频，现在可以切换了

### 预期行为
推荐视频未加载时正常切换分集

### 错误日志
Xiaomi Pad 6 Pro
MIUI 14 (Android 13)
```
PiliPalaX错误日志 
 ********************
------- 设备信息 -------
id: TKQ1.221114.001
board: taro
bootloader: unknown
brand: Xiaomi
device: liuqin
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/liuqin/liuqin:13/TKQ1.221114.001/V14.0.9.0.TMYCNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-325346-130jb-gqm5r-2ckkr
isPhysicalDevice: true
manufacturer: Xiaomi
model: 23046RP50C
product: liuqin
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.9.0.TMYCNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-09-01
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPalaX
buildNumber: 1483
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
"ReleatedController" not found. You need to call "Get.put(ReleatedController())" or "Get.lazyPut(()=>ReleatedController())"
------- 错误堆栈 -------
#0      GetInstance.find (package:get/get_instance/src/get_instance.dart:306)
#1      Inst.find (package:get/get_instance/src/extension_instance.dart:69)
#2      VideoIntroController.changeSeasonOrbangu (package:PiliPalaX/pages/video/detail/introduction/controller.dart:484)
#3      _PagesPanelState.build.<anonymous closure>.<anonymous closure> (package:PiliPalaX/pages/video/detail/introduction/widgets/page.dart:131)
#4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#17     _invoke1 (dart:ui/hooks.dart:328)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
------- CUSTOM INFO -------
```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。
在原版也有[类似的问题](https://github.com/guozhigq/pilipala/issues/681)
https://github.com/orz12/pilipala/assets/55239052/2a23060e-91e6-40f7-b12f-7c754c706f31

**Comment by orz12** [comment]
这个是视频介绍未加载导致的 修起来有点小麻烦 后续思考一下

**Comment by orz12** [comment]
修好了。
